# Generated by Django 5.1.1 on 2024-11-19 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenements', '0005_evenement_approved'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvenementAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Evenement name')),
                ('evenement_date', models.DateTimeField(verbose_name='Evenement date')),
                ('description', models.TextField(blank=True)),
                ('approved', models.BooleanField(default=True, verbose_name='Approved')),
                ('attendees', models.ManyToManyField(blank=True, to='evenements.monclubuser')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='evenements.venue')),
            ],
        ),
    ]
