# Generated by Django 5.1.1 on 2024-11-29 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenements', '0008_delete_evenementadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/'),
        ),
    ]
