# Generated by Django 5.1.1 on 2024-12-03 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenements', '0010_alter_evenement_attendees_alter_venue_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='attendees',
            field=models.ManyToManyField(blank=True, to='evenements.monclubuser'),
        ),
    ]
