# Generated by Django 5.1.1 on 2024-12-03 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenements', '0011_alter_evenement_attendees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evenement',
            name='attendees',
        ),
        migrations.AddField(
            model_name='evenement',
            name='attendees',
            field=models.CharField(blank=True, max_length=120, verbose_name='Event Attendees'),
        ),
    ]
