# Generated by Django 5.1.1 on 2024-12-03 16:51

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenements', '0012_remove_evenement_attendees_evenement_attendees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='attendees',
            field=models.CharField(blank=True, max_length=120, verbose_name=django.contrib.auth.models.User),
        ),
    ]
